<a href="https://colab.research.google.com/github/vincent4u/vince-file/blob/main/Feedforward_Backward%20propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

class NN:
    def __init__(self, learn_rate=0.5, input_nodes=2, hidden_nodes=2, output_nodes=2):
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        self.learn_rate = learn_rate

        # Defining the layers and attributing random weights for each layer's nodes
        layers = [self.input_nodes] + [self.hidden_nodes] + [self.output_nodes]
        self.weight = []
        for i in range(len(layers) - 1):
            w = np.random.rand(layers[i], layers[i+1])
            self.weight.append(w)

    def __sigmoid(self, hidden_input):
        return 1 / (1 + np.exp(-1 * self.learn_rate * hidden_input))

    def forward_propagation(self, input):
        self.activations = [input]
        X_input = input
        for i, w in enumerate(self.weight):
            hidden_input = np.dot(X_input, w)
            activated_hidden_input = self.__sigmoid(hidden_input)
            self.activations.append(activated_hidden_input)
            X_input = activated_hidden_input
            print("Weight matrix at layer {}: \n{}".format(i+1, w))
        return activated_hidden_input

    def backward_propagation(self, targets):
        deltas = [None] * len(self.weight)
        error = targets - self.activations[-1]
        delta = error * self.activations[-1] * (1 - self.activations[-1])
        deltas[-1] = delta
        for i in reversed(range(len(deltas)-1)):
            error = np.dot(deltas[i+1], self.weight[i+1].T)
            delta = error * self.activations[i+1] * (1 - self.activations[i+1])
            deltas[i] = delta
        for i in range(len(self.weight)):
            gradient = np.dot(self.activations[i].T, deltas[i])
            self.weight[i] += self.learn_rate * gradient

if __name__ == "__main__":
    mlp = NN()
    input = np.random.rand(mlp.input_nodes)
    output = mlp.forward_propagation(input)
    targets = np.random.rand(mlp.output_nodes)

    print("The inputs are: {}".format(input))
    print("The outputs are: {}".format(output))
    print("The targets are: {}".format(targets))

    mlp.backward_propagation(targets)
    print("Updated weights after backward propagation:")
    for i, w in enumerate(mlp.weight):
        print("Weight matrix at layer {}: \n{}".format(i+1, w))

Weight matrix at layer 1: 
[[0.56800597 0.97613794]
 [0.46507298 0.86289871]]
Weight matrix at layer 2: 
[[0.72113144 0.39118098]
 [0.20292534 0.86608318]]
The inputs are: [0.54153222 0.3820902 ]
The outputs are: [0.56549693 0.59191404]
The targets are: [0.58892048 0.79621099]
Updated weights after backward propagation:
Weight matrix at layer 1: 
[[0.57157391 0.97970589]
 [0.46864093 0.86646665]]
Weight matrix at layer 2: 
[[0.73768846 0.407738  ]
 [0.21948236 0.8826402 ]]
