<a href="https://colab.research.google.com/github/vincent4u/vince-file/blob/main/Multilayer_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

class NN:
    def __init__(self, learn_rate=0.5, input_nodes=2, hidden_nodes=3, output_nodes=2):
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes
        self.learn_rate = learn_rate


        #Defining the layers and attributing random weights for each layers per nodes

        layers = [self.input_nodes] + [self.hidden_nodes]+ [self.output_nodes]
        self.weight = []
        for i in range(len(layers)-1):
            w = np.random.rand(layers[i], layers[i+1])
            self.weight.append(w)

    def __sigmoid(self, hidden_input):
        return 1 / (1 + np.exp(-1 * self.learn_rate * hidden_input))

    def forward_propagation(self, input):
        X_input = input
        for i,w in enumerate(self.weight):
            hidden_input = np.dot(X_input, w)
            activated_hidden_input = self.__sigmoid(hidden_input)
            X_input = activated_hidden_input
            print("Weight matrix at layer {}: \n{}".format(i+1, w))
        return activated_hidden_input

    # def backward_propagation(self, input,target):
    #   predictions=self.forward_propagation(input)  #i should have worked on this more
    #   error=target-predictions

if __name__ == "__main__":
    mlp = NN()
    input = np.random.rand(mlp.input_nodes)
    output = mlp.forward_propagation(input)

    print("The inputs are: {}".format(input))
    print("The outputs are: {}".format(output))

Weight matrix at layer 1: 
[[0.7436289  0.93327968 0.00656294]
 [0.36398197 0.20827025 0.40672811]]
Weight matrix at layer 2: 
[[0.89372475 0.45071784]
 [0.98790078 0.31990706]
 [0.59315556 0.26448397]]
The inputs are: [0.45953107 0.19110967]
The outputs are: [0.66226113 0.56978768]


Neural Network;
I developed the Neural network structure from the onset. Allowing the user to determine the number of nodes and the number of hidden layer. note if the network is to have multiple hidden layers say two hidden layers with 3 nodes for the first hidden layer and 5 nodes for the second hidden layer, then the structure would be changed from the def...as
def __init__(self, learn_rate=0.5, input_nodes=2, hidden_nodes=[3,5], output_nodes=2).
where the hidden nodes=[3,5] specifies the number of nodes for each of the hidden layer segments.